```yaml
apiVersion: v1
kind: Service
metadata:
  name: elysium-innovations-service
  labels:
    app: elysium-innovations
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: elysium-innovations
```